### ISSUE TITLE
Add representation of Main Supply Routes

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-LOG#13]
PCR # | Short Description | Module/Page | Problem/Proposal | TC/EC | Action | Note | Submitted by | Submission Date | Resolution | Last Update
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
COM_015 | Add representation of Main Supply   Routes | Logistics | Add representation of MSR to the   Logistics Module to represent named routes that can be referenced and used in   logistics operations and simulation control parameters (LBML). | TC | Add an object class representing   MSR with unique ID, unique name, route, capacity etc. |   | Björn Löfstrand, bjornl@pitch.se | 2018-06-20 |   |

**Comment by lofstrandbjorn** [comment]
NETN-SE supports generic Route objects. E.g. MSR representation.
