### ISSUE TITLE
Grammar and spelling corrections

### ISSUE THREAD

**Issue by sam-d-hall** [AMSP-04/NETN-LOG#17]
NETN-LOG.md:
- "...by subclassing to provide more **detail** information..." grammar
- "If the time, specified in the RequestTimeOut parameter, **pass** without" grammar
- "...and **on** optional..." grammar

NETN-LOG.xml:
- RequestRepair semantics grammar
- RequestTransport semantics - should this be "The request to be transported by, embark..."?
- OfferService semantics "the providing **entities** ability"
- AcceptOffer and ServiceStarted semantics grammar and consider more concise statement
- "SCP_ServiceStarted interaction" is mentioned but doesn't exist
- ReadyToReceiveService semantics grammar, and "later than"
- TransportDestroyedEntities semantics grammar - should this be "provider simulates"?

**Comment by lofstrandbjorn** [comment]
"...by subclassing to provide more detailed information..."

"If the time, specified in the `RequestTimeOut` parameter, pass, without an offer is received, the consumer shall cancel the service using `CancelRequest`. A `RequestId` parameter is required and indicates which service to cancel. After the cancellation, the logistics service pattern ends."

"...and an optional..."

**Comment by lofstrandbjorn** [comment]
- RequestRepair semantics grammar
"Sent by the consumer when a repair is needed."

- RequestTransport semantics - should this be "The request to be transported by, embark..."?
"Use a RequestTransport interaction to initiate a transport, embarkment or disembarkment of a platform."

- OfferService semantics "the providing entities ability"
"The OfferService is a response to a RequestService. Subclasses of this interaction for specific types of offers contain a more detailed description of the offer. This information may include when, where, how the service can be delivered."


- AcceptOffer and ServiceStarted semantics grammar and consider more concise statement
"Use the AcceptOffer interaction to accept an offer received in an OfferService interaction."

"Issued by a service provider to inform about the start of service delivery. The time of service delivery start may be significantly later than receiving an indication from the consumer that the service delivery can start."

- "SCP_ServiceStarted interaction" is mentioned but doesn't exist
Removed

- ReadyToReceiveService semantics grammar, and "later than"
"Issued by a service consumer to indicate that service delivery can start. The time of service delivery may be significantly later than indicating ready for service delivery."

- TransportDestroyedEntities semantics grammar - should this be "provider simulates"?
"Used by a service provider to update information on damage state of entities under transport."

All updated + missing Required/Optional indications for parameters also added.
